<a href="https://colab.research.google.com/github/josepeon/calculus_parsons/blob/main/neural_nets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import torch
import torch.nn as nn
import seaborn as sns

In [4]:
tips = sns.load_dataset('tips')

In [5]:
tips.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
X = tips[['total_bill']]
y = tips['tip']

In [15]:
model = nn.Linear(in_features = 1, out_features = 1)

In [16]:
list(model.parameters())

[Parameter containing:
 tensor([[0.5079]], requires_grad=True),
 Parameter containing:
 tensor([-0.5964], requires_grad=True)]

In [17]:
#Turn into Pytorch tensors
xt = torch.tensor(X.values, dtype = torch.float32)
yt = torch.tensor(y.values, dtype = torch.float32)

In [18]:
model(xt)

tensor([[ 8.0321],
        [ 4.6548],
        [10.0737],
        [11.4296],
        [11.8918],
        [12.2473],
        [ 3.8575],
        [13.0548],
        [ 7.0417],
        [ 6.9097],
        [ 4.6193],
        [17.3106],
        [ 7.2347],
        [ 8.7634],
        [ 6.9351],
        [10.3631],
        [ 4.6497],
        [ 7.6766],
        [ 8.0219],
        [ 9.8908],
        [ 8.5044],
        [ 9.7080],
        [ 7.4125],
        [19.4233],
        [ 9.4693],
        [ 8.4485],
        [ 6.1936],
        [ 5.8483],
        [10.4241],
        [ 9.3830],
        [ 4.2536],
        [ 8.7228],
        [ 7.0519],
        [ 9.9111],
        [ 8.4333],
        [11.6226],
        [ 7.6867],
        [ 8.0016],
        [ 8.8954],
        [15.2843],
        [ 7.5496],
        [ 8.2708],
        [ 6.4831],
        [ 4.3196],
        [14.8424],
        [ 8.6923],
        [10.6932],
        [15.8582],
        [13.9029],
        [ 8.5653],
        [ 5.7721],
        [ 4.6294],
        [17.

In [19]:
mse = nn.MSELoss()

In [20]:
yhat = model(xt)

In [22]:
mse(yt, yhat)

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([244, 1])) that is different to the input size (torch.Size([244])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor(63.9144, grad_fn=<MseLossBackward0>)

In [24]:
loss = mse(yt, yhat)

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([244, 1])) that is different to the input size (torch.Size([244])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [26]:
loss.backward()

In [27]:
import torch.optim as optim

In [28]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [29]:
yhat = model(xt) #make predictions
loss = (mse(yt, yhat)) #evaluate errors
loss.backward() #computes derivatives
optimizer.step() #steps down loss function one iteration

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:616: UserWarning: Using a target size (torch.Size([244, 1])) that is different to the input size (torch.Size([244])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [30]:
list(model.parameters())

[Parameter containing:
 tensor([[-6.2032]], requires_grad=True),
 Parameter containing:
 tensor([-0.8546], requires_grad=True)]

In [33]:
new_yhat = model(xt)

In [34]:
mse(yt, new_yhat)

tensor(19064.0488, grad_fn=<MseLossBackward0>)

In [ ]:
losses = []